INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('1', 'SOB', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('2', 'SOB', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('3', 'SOB', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('4', 'SOB', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('5', 'SOB', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('6', 'SOB', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('7', 'SUB', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('8', 'SUB', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('9', 'SUB', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('10', 'SUB', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('11', 'SUB', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('12', 'SUB', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('13', 'matching', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('14', 'matching', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('15', 'matching', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('16', 'matching', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('17', 'matching', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('18', 'matching', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('19', 'matching', 'BNP', 'BNP-1DBNP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('20', 'matching', 'SG', 'SG-1DSG');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('21', 'matching', 'CL', 'CL-1DCL');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('22', 'matching', 'SIPS', 'SIPS-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('23', 'matching', 'LAPOSTE', 'LAPOSTE-1DLAPOSTE');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('24', 'matching', 'yymmdd', '${e_date}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('25', 'matching', 'yyyymmdd', '${e_date1}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('26', 'matching', 'yyyy_mm_dd', '${e_date2}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('27', 'matching', 'yyyymmdd_HHMMSS', '${e_date3}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('28', 'matching', 'yyyymmddHHMMSS0000', '${e_date4}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('29', 'matching', 'ddmmyyyy', '${e_date5}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('30', 'matching', 'ddmmyy', '${e_date6}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('31', 'matching', 'yyyymmdd.HHMMSS', '${e_date7}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('32', 'matching', '1 day ago yyyymmdd', '${e_datev}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('33', 'matching', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('34', 'matching', '0', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('35', 'matching', '1', 'delete');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('36', 'matching', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('37', 'matching', '1', 'DUPLI_1');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('38', 'matching', '2', 'DUPLI_2');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('39', 'matching', '3', 'DUPLI_3');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('40', 'matching', '4', 'DUPLI_4');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('41', 'matching', '5', 'DUPLI_5');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('42', 'matching', '6', 'DUPLI_6');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('43', 'chargeback', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('44', 'chargeback', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('45', 'chargeback', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('46', 'chargeback', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('47', 'chargeback', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('48', 'chargeback', 'BNP', 'BNP-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('49', 'chargeback', 'SG', 'SG-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('50', 'chargeback', 'CL', 'CL-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('51', 'chargeback', 'SIPS', 'SIPS-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('52', 'chargeback', 'LAPOSTE', 'LAPOSTE-1D');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('53', 'chargeback', 'yymmdd', '${e_date}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('54', 'chargeback', 'yyyymmdd', '${e_date1}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('55', 'chargeback', 'yyyy_mm_dd', '${e_date2}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('56', 'chargeback', 'yyyymmdd_HHMMSS', '${e_date3}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('57', 'chargeback', 'yyyymmddHHMMSS0000', '${e_date4}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('58', 'chargeback', 'ddmmyyyy', '${e_date5}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('59', 'chargeback', 'ddmmyy', '${e_date6}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('60', 'chargeback', 'yyyymmdd.HHMMSS', '${e_date7}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('61', 'chargeback', '1 day ago yyyymmdd', '${e_datev}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('62', 'chargeback', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('63', 'chargeback', '0', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('64', 'chargeback', '1', 'delete');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('65', 'chargeback', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('66', 'chargeback', '1', 'DUPLI_1');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('67', 'chargeback', '2', 'DUPLI_2');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('68', 'chargeback', '3', 'DUPLI_3');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('69', 'chargeback', '4', 'DUPLI_4');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('70', 'chargeback', '5', 'DUPLI_5');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('71', 'chargeback', '6', 'DUPLI_6');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('72', 'wallet', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('73', 'wallet', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('74', 'wallet', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('75', 'wallet', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('76', 'wallet', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('77', 'wallet', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('78', 'wallet', 'yymmdd', '${e_date}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('79', 'wallet', 'yyyymmdd', '${e_date1}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('80', 'wallet', 'yyyy_mm_dd', '${e_date2}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('81', 'wallet', 'yyyymmdd_HHMMSS', '${e_date3}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('82', 'wallet', 'yyyymmddHHMMSS0000', '${e_date4}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('83', 'wallet', 'ddmmyyyy', '${e_date5}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('84', 'wallet', 'ddmmyy', '${e_date6}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('85', 'wallet', 'yyyymmdd.HHMMSS', '${e_date7}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('86', 'wallet', '1 day ago yyyymmdd', '${e_datev}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('87', 'wallet', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('88', 'wallet', '0', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('89', 'wallet', '1', 'delete');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('90', 'wallet', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('91', 'wallet', '1', 'DUPLI_1');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('92', 'wallet', '2', 'DUPLI_2');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('93', 'wallet', '3', 'DUPLI_3');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('94', 'wallet', '4', 'DUPLI_4');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('95', 'wallet', '5', 'DUPLI_5');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('96', 'wallet', '6', 'DUPLI_6');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('97', 'operation', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('98', 'operation', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('99', 'operation', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('100', 'operation', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('101', 'operation', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('102', 'operation', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('103', 'operation', 'yymmdd', '${e_date}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('104', 'operation', 'yyyymmdd', '${e_date1}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('105', 'operation', 'yyyy_mm_dd', '${e_date2}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('106', 'operation', 'yyyymmdd_HHMMSS', '${e_date3}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('107', 'operation', 'yyyymmddHHMMSS0000', '${e_date4}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('108', 'operation', 'ddmmyyyy', '${e_date5}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('109', 'operation', 'ddmmyy', '${e_date6}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('110', 'operation', 'yyyymmdd.HHMMSS', '${e_date7}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('111', 'operation', '1 day ago yyyymmdd', '${e_datev}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('112', 'operation', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('113', 'operation', '0', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('114', 'operation', '1', 'delete');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('115', 'operation', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('116', 'operation', '1', 'DUPLI_1');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('117', 'operation', '2', 'DUPLI_2');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('118', 'operation', '3', 'DUPLI_3');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('119', 'operation', '4', 'DUPLI_4');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('120', 'operation', '5', 'DUPLI_5');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('121', 'operation', '6', 'DUPLI_6');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('122', 'transaction', 'ftp', 'atosftp');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('123', 'transaction', 'sftp', 'atossftpr');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('124', 'transaction', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('125', 'transaction', 'zip', '.ZIP');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('126', 'transaction', 'csv', '.CSV');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('127', 'transaction', 'xml', '.XML');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('128', 'transaction', 'yymmdd', '${e_date}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('129', 'transaction', 'yyyymmdd', '${e_date1}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('130', 'transaction', 'yyyy_mm_dd', '${e_date2}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('131', 'transaction', 'yyyymmdd_HHMMSS', '${e_date3}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('132', 'transaction', 'yyyymmddHHMMSS0000', '${e_date4}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('133', 'transaction', 'ddmmyyyy', '${e_date5}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('134', 'transaction', 'ddmmyy', '${e_date6}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('135', 'transaction', 'yyyymmdd.HHMMSS', '${e_date7}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('136', 'transaction', '1 day ago yyyymmdd', '${e_datev}');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('137', 'transaction', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('138', 'transaction', '0', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('139', 'transaction', '1', 'delete');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('140', 'transaction', '', '');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('141', 'transaction', '1', 'DUPLI_1');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('142', 'transaction', '2', 'DUPLI_2');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('143', 'transaction', '3', 'DUPLI_3');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('144', 'transaction', '4', 'DUPLI_4');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('145', 'transaction', '5', 'DUPLI_5');
INSERT INTO `test`.`transcode` (`TRANSCODE_ID`, `LOG_TYPE`, `DB_VALUE`, `CONF_VALUE`) VALUES ('146', 'transaction', '6', 'DUPLI_6');

INSERT INTO `test`.`client` (`CLIENT_ID`, `MERCHANT_ID`, `SIPS_ALIAS`, `ENVIRONMENT`, `PROTOCOL`, `BANK_NAME`, `MERCHANT_FTP`) VALUES ('1', '000000000000001', 'Myawsumshop', 'production', 'ftp', 'CL', 'ubzawsum');
INSERT INTO `test`.`client` (`CLIENT_ID`, `MERCHANT_ID`, `SIPS_ALIAS`, `ENVIRONMENT`, `PROTOCOL`, `BANK_NAME`, `MERCHANT_FTP`) VALUES ('2', '000000000000002', 'GunsNRoses', 'acceptance', 'sftp', 'BNP', 'ubzrock');
INSERT INTO `test`.`client` (`CLIENT_ID`, `MERCHANT_ID`, `SIPS_ALIAS`, `ENVIRONMENT`, `PROTOCOL`, `BANK_NAME`, `MERCHANT_FTP`) VALUES ('3', '000000000000003', 'Metallica', 'production', 'ftp', 'SIPS', 'ubzrock');
INSERT INTO `test`.`client` (`CLIENT_ID`, `MERCHANT_ID`, `SIPS_ALIAS`, `ENVIRONMENT`, `PROTOCOL`, `BANK_NAME`, `MERCHANT_FTP`) VALUES ('4', '000000000000004', 'FooFighters', 'production', 'ftp', 'LAPOSTE', 'ubzrock');
INSERT INTO `test`.`client` (`CLIENT_ID`, `MERCHANT_ID`, `SIPS_ALIAS`, `ENVIRONMENT`, `PROTOCOL`, `BANK_NAME`, `MERCHANT_FTP`) VALUES ('5', '000000000000005', 'Deadmau5', 'production', 'sftp', 'SG', 'ubzelectro');

INSERT INTO `test`.`teams` (`TEAMS_ID`, `TEAMS_NAME`) VALUES ('1', 'TeamWin');

INSERT INTO `test`.`employee` (`EMPLOYEE_ID`, `EMPLOYEE_NAME`, `TEAMS_ID`) VALUES ('1', 'test TEST', '1');

INSERT INTO `test`.`project` (`PROJECT_ID`, `LABEL`, `START_DATE`, `TARGET_DATE`, `END_DATE`, `PROJECT_STATUS`) VALUES ('1', 'init', '2018-02-07', '2018-02-07', '2018-02-07', '1');

INSERT INTO `test`.`configuration` (`CONFIGURATION_ID`, `PROFILE`, `NAME_FILE`, `NAME_ZIP`, `OCCURENCE`, `LIST_SERV`, `RELEASES`, `EXTENTION`, `DATE_FORMAT`, `PROJECT_ID`, `CLIENT_ID`) VALUES ('1', 'RAPPROCHEMENTS', 'rapban', 'RAPBAN', '01', 'tpsips53v;tpsips53s;tpsips54v;tpsips54s', '1.0.1', 'zip', 'yymmdd', '1', '1');
INSERT INTO `test`.`configuration` (`CONFIGURATION_ID`, `PROFILE`, `NAME_FILE`, `NAME_ZIP`, `OCCURENCE`, `LIST_SERV`, `RELEASES`, `EXTENTION`, `DATE_FORMAT`, `PROJECT_ID`, `CLIENT_ID`) VALUES ('2', 'IMPAYES', 'jri', 'JRI', '01', 'tpsips53v;tpsips53s;tpsips54v;tpsips54s', '1.0.1', 'csv', 'yyyymmdd', '1', '2');
INSERT INTO `test`.`configuration` (`CONFIGURATION_ID`, `PROFILE`, `NAME_FILE`, `NAME_ZIP`, `OCCURENCE`, `LIST_SERV`, `RELEASES`, `EXTENTION`, `DATE_FORMAT`, `PROJECT_ID`, `CLIENT_ID`) VALUES ('3', 'CARTE-ECHUES', 'extract', 'EXTRACT', '02', 'tpsips53v;tpsips53s;tpsips54v;tpsips54s', '1.0.1', 'zip', 'yymmdd', '1', '3');
INSERT INTO `test`.`configuration` (`CONFIGURATION_ID`, `PROFILE`, `NAME_FILE`, `NAME_ZIP`, `OCCURENCE`, `LIST_SERV`, `RELEASES`, `EXTENTION`, `DATE_FORMAT`, `PROJECT_ID`, `CLIENT_ID`) VALUES ('4', 'IMPAYES', 'jri', 'JRI', '03', 'tpsips53v;tpsips53s;tpsips54v;tpsips54s', '1.0.1', 'zip', 'yymmdd', '1', '4');
INSERT INTO `test`.`configuration` (`CONFIGURATION_ID`, `PROFILE`, `NAME_FILE`, `NAME_ZIP`, `OCCURENCE`, `LIST_SERV`, `RELEASES`, `EXTENTION`, `DATE_FORMAT`, `PROJECT_ID`, `CLIENT_ID`) VALUES ('5', 'RAPPROCHEMENTS', 'rapban', 'RAPBAN', '01', 'tpsips53v;tpsips53s;tpsips54v;tpsips54s', '1.0.1', 'zip', 'yymmdd', '1', '5');
